### ISSUE TITLE
Version 1.0.0 release

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/jekyll-theme-legumeinfo#35]
With the LIS Jekyll site moving back to the theme and multiple other sites now depending on it, I think it's time we start tagging releases so we know that people are actually using official release instead of whatever version of the `main` branch they happened to pull. The following is a list of tasks that need to be completed before we make our first release:

- [x] legumeinfo/jekyll-theme-legumeinfo#19
- [x] legumeinfo/jekyll-theme-legumeinfo#34
- [x] legumeinfo/jekyll-theme-legumeinfo#33
- [x] legumeinfo/jekyll-theme-legumeinfo#27
- [x] legumeinfo/jekyll-theme-legumeinfo#10
- [x] legumeinfo/jekyll-theme-legumeinfo#39
- [x] legumeinfo/jekyll-theme-legumeinfo#51
- [x] legumeinfo/jekyll-theme-legumeinfo#54 
- [x] legumeinfo/jekyll-theme-legumeinfo#55
- [x] ~~legumeinfo/jekyll-starter-legumeinfo#12~~
- [x] legumeinfo/jekyll-theme-legumeinfo#59

**Comment by alancleary** [comment]
Done in PR #97.
